# Testnet Deployment Plan
id = 0
name = "Testnet Deployment"
network = "testnet"
stacks-node = "https://stacks-node-api.testnet.stacks.co"

[[plan.batches]]
id = 0

  [[plan.batches.transactions]]
  contract-publish = {
    contract-name = "all-traits",
    expected-sender = "ST3PPMPR7SAY4CAKQ4ZMYC2Q9FAVBE813YWNJ4JE6",
    cost = 5000,
    path = "contracts/traits/all-traits.clar",
    anchor-block-only = true,
    clarity-version = 3,
    epoch = "3.0"
  }

  [[plan.batches.transactions]]
  contract-publish = {
    contract-name = "cxd-token",
    expected-sender = "ST3PPMPR7SAY4CAKQ4ZMYC2Q9FAVBE813YWNJ4JE6",
    cost = 10000,
    path = "contracts/tokens/cxd-token.clar",
    anchor-block-only = true,
    clarity-version = 3,
    epoch = "3.0"
  }

  [[plan.batches.transactions]]
  contract-publish = {
    contract-name = "governance-token",
    expected-sender = "ST3PPMPR7SAY4CAKQ4ZMYC2Q9FAVBE813YWNJ4JE6",
    cost = 10000,
    path = "contracts/governance/governance-token.clar",
    anchor-block-only = true,
    clarity-version = 3,
    epoch = "3.0"
  }
