
[network]
name = "devnet"
[accounts]
deployer = "ST3N0ZC9HBPDEBEJ1H1QFGMJF3PSNGW3FYZSVN513"
wallet_1 = "ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5"
wallet_2 = "ST2NEB84ASENDXKYGJPQW86YXQCEFEX2ZQPG87ND"
wallet_3 = "ST2REHHS5J3CERCRBEPMGH7921Q6PYKAADT7JP2VB"
