[accounts.deployer]
balance = 100000000000000
address = "STSZXAKV7DWTDZN2601WR31BM51BD3YTQXKCF9EZ"

[accounts.wallet_1]
balance = 100000000000000

[accounts.wallet_2]
balance = 100000000000000

[network]
name = "testnet"
node_rpc_address = "https://stacks-node-api.testnet.stacks.co"
node_p2p_address = "https://stacks-node-api.testnet.stacks.co"

[devnet]
stacks_node = "https://stacks-node-api.testnet.stacks.co"
bitcoin_node = "https://mempool.space/testnet/api"

[costs]
contract_publish = 1000000

[deployment]
max_fee = 1000000
fee_rate = 10
anchor_block_only = true

[contracts]
# All contracts will be deployed with these default settings
clarity_version = 3
epoch = "3.0"

# Specific contract overrides can be added here if needed
[contracts.all-traits]
cost = 1000000

[contracts.cxd-token]
cost = 1000000

[contracts.governance-token]
cost = 1000000
