[project]
name = "Conxian"
description = "Foundation-only manifest to bootstrap compilation and iterate upward."
clarinet_version = "3.8.1"

[accounts.deployer]
address = "STSZXAKV7DWTDZN2601WR31BM51BD3YTQXKCF9EZ"

[contracts.all-traits]
path = "../contracts/traits/all-traits.clar"
clarity_version = 3
epoch = "3.0"

[contracts.utils-encoding]
path = "../contracts/utils/encoding.clar"
clarity_version = 3
epoch = "3.0"

[contracts.block-utils]
path = "../contracts/utils/block-utils.clar"
clarity_version = 3
epoch = "3.0"

[contracts.dim-registry]
path = "../contracts/dimensional/dim-registry.clar"
clarity_version = 3
epoch = "3.0"
depends_on = ["all-traits"]

[contracts.dimensional-oracle]
path = "../contracts/oracle/dimensional-oracle.clar"
clarity_version = 3
epoch = "3.0"
depends_on = ["all-traits", "utils-encoding"]

[contracts.dimensional-advanced-router-dijkstra]
path = "../contracts/dimensional/advanced-router-dijkstra.clar"
clarity_version = 3
epoch = "3.0"
depends_on = ["all-traits"]

[contracts.dimensional-position-nft]
path = "../contracts/dimensional/position-nft.clar"
clarity_version = 3
epoch = "3.0"
depends_on = ["all-traits"]

[contracts.dimensional-concentrated-liquidity-pool-v2]
path = "../contracts/dimensional/concentrated-liquidity-pool-v2.clar"
clarity_version = 3
epoch = "3.0"
depends_on = ["all-traits"]

[contracts.risk-risk-manager]
path = "../contracts/risk/risk-manager.clar"
clarity_version = 3
epoch = "3.0"
depends_on = ["all-traits", "utils-encoding"]

[contracts.monitoring-finance-metrics]
path = "../contracts/monitoring/finance-metrics.clar"
clarity_version = 3
epoch = "3.0"
depends_on = ["all-traits"]

